### PR TITLE
Xcode9 prototype issue fix

### LINKED ISSUE #115: Xcode 9 prototype function issues
Hi,

After enabling xcode 9 preferred build settings ReactiveObjc fails to build with several declaration is not a prototype errors.

The fix should be easy so should I submit a PR for this ?

Thanks,

### PR DESCRIPTION
**Pull request by andersio**
Resolves #115.
Preceded by #119 and #122.

### CODE REVIEW

**Comment by andersio** [comment]
@mdiep Since it could be source breaking, should we bump to 4.0? 🤔

**Comment by mdiep** [comment]
I don't think this is source breaking. The only change that could be is the `EXTScope.h` part; but that's an implementation detail. It shouldn't be considered public API.

**Comment by andersio** [comment]
I have changed the signature of `zip` here though, which now has a generic return type like `combineLatest`.

**Comment by mdiep** [comment]
Ah, I missed that bit. Still, I think that qualifies as a bug fix. Objective-C should be more tolerant of a change like that.

**Pull request merged**
