### PR TITLE
Increase version to 2.2.0

### PR DESCRIPTION
**Pull request by erichoracek**
Includes #75, #80, #81, #82, #83, #85, #87, and #88.

As far as I can tell, this should have no breaking changes.

### CODE REVIEW

**Comment by andersio** [comment]
It breaks in Swift though, if it is a primary concern.

**Comment by erichoracek** [comment]
Shouldn't that be communicated by releasing a breaking change to ReactiveObjCBridge? Since there are equivalent APIs in ReactiveSwift for all constructs in ReactiveObjC, my interpretation is that we're expecting consumers of ReactiveObjC to be pure Obj-C, and bridged to Swift exclusively through ReactiveObjCBridge.

**Comment by andersio** [comment]
We do provide a bridge, but not everyone uses it. There is a crowd that uses only the imported ReactiveObjC API.

**Comment by erichoracek** [comment]
Sounds reasonable—I'll go ahead and make it a major release then.

**Pull request closed without merging**
