### PR TITLE
More type annotations

### PR DESCRIPTION
**Pull request by erwald**
This pull request adds generics to `RACMulticastConnection`, `RACBehaviorSubject` and type annotations to `RACSignal`'s `+empty` and `+return` methods.

It seems to me that it'd also make sense to add generics to `RACChannelTerminal`, `RACChannel` and `RACSubject`. Thoughts on that?

### CODE REVIEW

**Comment by erichoracek** [comment]
This is great!

Aren't some of these classes private to the implementation to ReactiveObjC? E.g. `RACEmptySignal` and `RACReturnSignal`? What is the benefit of making them generic?

Re: `RACSubject`, as far as I can tell from our usage of the existing generics, it should be possible to make `RACSubject` generic to its value type since it is a direct subclass of `RACSignal`. This should work in the same way that `NSMutableArray` generic element type works with `NSArray`.

Re: `RACChannel`/`RACChannelTerminal`, that should work as well if you want to take a stab at it.

**Comment by erwald** [comment]
Yes, true, for `RACEmptySignal` and `RACReturnSignal` generics are not much use practically; I added it more on theoretical grounds. It makes sense to me semantically that a `RACEmptySignal` and `RACReturnSignal` has one associated type just like `RACSignal` does. But maybe it's just noise. Should I revert those changes?

Meanwhile, it seems the Travis CI build failed, although everything was hunky dory when running the tests locally. I'll have a look at that.

**Comment by erichoracek** [comment]
That seems reasonable re: the internal types—it doesn't add any overhead to consumers.

**Comment by erwald** [comment]
All right, so I'll keep it as it is, then.

As for the failing Travis CI build, it seems to be a failure in three tests related to intervals. I don't see how that could possibly be caused by these type changes, and, moreover, the same tests pass  locally.

Is it possible that the tests themselves are fickle, or that there are problems with the CI environment?

**Comment by erwald** [comment]
@erichoracek Possible to merge?

**Pull request merged**
