### PR TITLE
RACBlockTrampoline: remove `NSInvocation` usage.

### PR DESCRIPTION
**Pull request by StatusReport**
There are two optimizations that are done in this commit:
1. Avoid allocating a `RACBlockTrampoline` object on every invocation.
2. Do not use the very slow `NSInvocation`, and instead hard-code the
block calls.

### CODE REVIEW

**Comment by erichoracek** [comment]
This seems reasonable to me—I can't see any reason why `NSInvocation` was needed in the first place here. However, since `RACBlockTrampoline` is now never instantiated can this just become a C function?

As with #107 it may be worth providing some comparative benchmarks as well.

**Comment by StatusReport** [comment]
It can definitely become a C function. I wanted to perform minimal changes to the code, but I can definitely do that if you'd like.

Benchmarks are coming soon. Busy days :)

**Comment by andersio** [comment]
Swift numbers, if it helps. Though obviously the ObjC runtime does more work than `RACBlockTrampoline`.
https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3362

**Comment by StatusReport** [comment]
Times for subject that receives 100K `RACTuple`s of 4 strings and uses `reduceEach` to map them to `nil`:

```
Simulator: 0.618836 sec vs. 0.987838 sec (x1.6 improvement)
iPhone 6S: 1.05445 sec vs 1.61 sec (x1.5 improvement)
```

**Comment by StatusReport** [comment]
If this is still of interest to anyone, [our fork](https://github.com/Lightricks/ReactiveObjC) contains this change and additional bug fixes and performance optimizations.

**Pull request closed without merging**
